services:
  frontend:
    build:
      context: ./app/
    ports:
      - 3000:3000
    volumes:
      - ./app/src:/app/src
  
  server:
    build:
      context: ./server/
    ports:
      - 3001:3001
    volumes:
      - ./server:/app

  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  database:
    image: mariadb:10.6
    restart: unless-stopped
    ports:
      # Make the DB accessible from outside of the Docker network if needed
      - 3309:3308
    volumes:
      # Mount a volume for mariadb's persistent files for lifecylce outside of stack
      - "./database/data:/var/lib/mysql"
      # Mount the db_schema directory into the container to be auto-read and created in the new db
      - "./database/db_schema:/docker-entrypoint-initdb.d"
