name: JavaScript Lint Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install Server Dependencies
      run: npm install
      working-directory: server

    - name: Lint Server
      run: npm run lint
      working-directory: server

    - name: Install App Dependencies
      run: npm install
      working-directory: app

    - name: Lint App
      run: npm run lint
      working-directory: app



